[ids]
*

[main]
# UK keyboard fixes
102nd = grave
backslash = 102nd

# Swap Ctrl and Alt keys (Mac style)
# control = layer(alt)
# alt = layer(control)
# rightalt = layer(control)

# Keep tmux prefix as Ctrl+b when using physical Ctrl key
# [alt]
# b = C-b

# UK keyboard control fixes
[control]
2 = G-4
3 = backslash


# UK keyboard shift fixes
[shift]
102nd = S-backslash
backslash = S-102nd
apostrophe = S-2
2 = S-apostrophe

