---
- hosts: localhost
  vars_files:
    - vars/main.yml
  roles:
    - role: software-common-non-gui
      tags: non-gui

    - role: software-common-gui
      tags: gui

    - role: aliases
      tags: aliases

    - role: keychron-k2
      tags: keyboard

    - role: zsh-antidote
      tags: shell

    - role: languages
      tags: langs
      depends_on:
        - zsh-antidote
