---
# tasks file for software-common-non-gui
- name: Install common packages
  apt:
    pkg:
      - vim
      - tmux
      - python3-venv
      - curl
      - gcc
      - build-essential
      - aspell
      - wordnet

- name: Clone Tmux plugin manager
  become: yes
  become_user: "{{ default_user }}"
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: Create Tmux conf file with plugins
  become: yes
  become_user: "{{ default_user }}"
  copy:
    dest: ~/.tmux.conf
    content: |
      set-option -g status-position bottom
      set-option -g repeat-time 0
      # List of plugins
      set -g @plugin 'tmux-plugins/tpm'
      set -g @plugin 'tmux-plugins/tmux-sensible'
      set -g @plugin 'tmux-plugins/tmux-resurrect'
      # Initialize TMUX plugin manager (TPM) - (keep this line at the very bottom of tmux.conf)
      run '~/.tmux/plugins/tpm/tpm'

- name: Post Tmux plugin manager install
  debug:
    msg:
      - "To finalise the Tmux plugin installation:"
      - "Open tmux"
      - "Source the conf file: 'tmux source ~/.tmux.conf'"
      - "Run the plugin install: prefix + I"
