---
# tasks file for software-common-gui
- name: Install optionals check
  pause:
    prompt: "Install all optionals? (yes/no)?"
  register: install_all_optionals

# KITTY TERMINAL INSTALL
- name: Install Kitty check
  pause:
    prompt: "Install kitty terminal (yes/no)?"
  register: install_kitty
  when: not install_all_optionals.user_input | bool

- name: Install Kitty terminal
  when: (install_all_optionals.user_input | bool) or
    (install_kitty.user_input | bool)
  block:

    - name: Download Kitty installer script
      get_url:
        url: https://sw.kovidgoyal.net/kitty/installer.sh
        dest: "/home/{{ default_user }}/installer.sh"
        mode: '0755'

    - name: Run Kitty installer script
      become: true
      become_user: "{{ default_user }}"
      shell: "~/installer.sh"

    - name: Ensure ~/.local/bin/ directory exists
      become: true
      become_user: "{{ default_user }}"
      file:
        path: "~/.local/bin/"
        state: directory

    - name: Create symbolic links for Kitty and Kitten executables
      become: true
      become_user: "{{ default_user }}"
      file:
        src: "~/.local/kitty.app/bin/{{ item }}"
        dest: "~/.local/bin/{{ item }}"
        state: link
      loop:
        - kitty
        - kitten

    - name: Copy the kitty.desktop file to ~/.local/share/applications so it can be found by the OS
      become: true
      become_user: "{{ default_user }}"
      copy:
        src: "/home/{{ default_user }}/.local/kitty.app/share/applications/kitty.desktop"
        dest: "/home/{{ default_user }}/.local/share/applications/"

    - name: Modify kitty.desktop with the correct icon path
      become: true
      become_user: "{{ default_user }}"
      replace:
        path: "~/.local/share/applications/kitty.desktop"
        regexp: 'Icon=kitty'
        replace: 'Icon=/home/{{ default_user }}/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png'

    - name: Modify kitty.desktop with the correct exec path
      become: true
      become_user: "{{ default_user }}"
      replace:
        path: "~/.local/share/applications/kitty.desktop"
        regexp: 'Exec=kitty'
        replace: 'Exec=/home/{{ default_user }}/.local/kitty.app/bin/kitty'

    - name: Remove downloaded installer script
      become: true
      become_user: "{{ default_user }}"
      file:
        path: "~/installer.sh"
        state: absent

# CHROMIUM INSTALL
- name: Install Chromium check
  pause:
    prompt: "Install chromium-browser (yes/no)?"
  register: install_chromium
  when: not install_all_optionals.user_input | bool

- name: Install Chromium
  apt:
    pkg:
      - chromium-browser
  when: (install_all_optionals.user_input | bool) or
    (install_chromium.user_input | bool)

# KEEPASSXC INSTALL
- name: Install KeepassXC check
  pause:
    prompt: "Install KeePassXC (yes/no)?"
  register: install_keepassxc
  when: not install_all_optionals.user_input | bool

- name: Install KeepassXC
  flatpak:
    name: org.keepassxc.KeePassXC
    state: present
  when: (install_all_optionals.user_input | bool) or
    (install_keepassxc.user_input | bool)

# KDENLIVE INSTALL
- name: Install Kdenlive check
  pause:
    prompt: "Install Kdenlive (yes/no)?"
  register: install_kdenlive
  when: not install_all_optionals.user_input | bool

- name: Install Kdenlive
  apt:
    pkg:
      - kdenlive
  when: (install_all_optionals.user_input | bool) or
    (install_kdenlive.user_input | bool)

# GIMP INSTALL
- name: Install GIMP check
  pause:
    prompt: "Install GIMP (yes/no)?"
  register: install_gimp
  when: not install_all_optionals.user_input | bool

- name: Install GIMP
  apt:
    pkg:
      - gimp
  when: (install_all_optionals.user_input | bool) or
    (install_gimp.user_input | bool)

# PEEK INSTALL
- name: Install Peek check
  pause:
    prompt: "Install Peek (yes/no)?"
  register: install_peek
  when: not install_all_optionals.user_input | bool

- name: Install Peek
  apt:
    pkg:
      - peek
  when: (install_all_optionals.user_input | bool) or
    (install_peek.user_input | bool)

# YAKUAKE INSTALL
- name: Install Yakuake check
  pause:
    prompt: "Install Yakuake (yes/no)?"
  register: install_yakuake
  when: not install_all_optionals.user_input | bool

- name: Install Yakuake
  apt:
    pkg:
      - yakuake
  when: (install_all_optionals.user_input | bool) or
    (install_yakuake.user_input | bool)

# VS CODE INSTALL
- name: Install Visual Studio Code check
  pause:
    prompt: "Install Visual Studio Code (yes/no)?"
  register: install_vscode
  when: not install_all_optionals.user_input | bool


- name: Install Visual Studio Code
  when: (install_all_optionals.user_input | bool) or
    (install_vscode.user_input | bool)
  block:

    - name: Run Microsoft repository and GPG key setup script
      shell: |
        sudo apt-get install wget gpg
        wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
        sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
        echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" |sudo tee /etc/apt/sources.list.d/vscode.list > /dev/null
        rm -f packages.microsoft.gpg

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Visual Studio Code
      apt:
        name: code
        state: present


